import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    welcome: 'Welcome to Kerala Migrant Health Portal',
    welcomeRoghar: 'Welcome to ROGHAR',
    startConsultation: 'Start Consultation',
    emergencySOS: 'Emergency SOS',
    nearbyServices: 'Nearby Medical Services',
    reminders: 'Reminders',
    addReminder: 'Add Reminder',
    voiceInput: 'Voice Input',
    speakToMe: 'Speak to Me',
    listening: 'Listening...',
    uploadReport: 'Upload Report',
    downloadReport: 'Download Report',
    generateQR: 'Generate QR Code',
    feedback: 'Feedback',
    healthTips: 'Health Tips',
    governmentSchemes: 'Government Schemes',
    leaveComment: 'Leave Comment',
    videoCall: 'Video Call',
    joinCall: 'Join Call',
    endCall: 'End Call',
    workerLogin: 'Worker Login',
    doctorLogin: 'Doctor Login',
    workerSignup: 'Worker Signup',
    doctorSignup: 'Doctor Signup',
    signup: 'Sign Up',
    login: 'Login',
    aadharNumber: 'Aadhar Number',
    abhaId: 'ABHA ID',
    password: 'Password',
    name: 'Name',
    phone: 'Phone Number',
    address: 'Address',
    healthRecords: 'Health Records',
    testReports: 'Test Reports',
    bookAppointment: 'Book Appointment',
    dashboard: 'Dashboard',
    logout: 'Logout',
    appointments: 'Appointments',
    patients: 'Patients',
    profile: 'Profile',
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    malayalam: 'Malayalam',
    bengali: 'Bengali',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    date: 'Date',
    time: 'Time',
    doctor: 'Doctor',
    hospital: 'Hospital',
    status: 'Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    selectHospital: 'Select Hospital',
    selectDoctor: 'Select Doctor',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    reason: 'Reason for Visit',
    symptoms: 'Symptoms',
    uploadReport: 'Upload Report',
    downloadReport: 'Download Report',
    reportDate: 'Report Date',
    reportType: 'Report Type',
    bloodTest: 'Blood Test',
    xray: 'X-Ray',
    mri: 'MRI',
    ct: 'CT Scan',
    other: 'Other',
    medicineInfo: 'Medicine Information',
    searchMedicines: 'Search Medicines',
    filterByType: 'Filter by Type',
    viewDetails: 'View Details',
    dosage: 'Dosage',
    sideEffects: 'Side Effects',
    precautions: 'Precautions',
    description: 'Description',
    usage: 'Usage',
    noMedicineFound: 'No information available, please try another medicine',
    medicalDisclaimer: 'Medical Disclaimer',
    mockupDashboard: 'Live Dashboard',
    hospitalMap: 'Hospital Map',
    qrGenerator: 'QR Generator',
    whySafe: 'Why Safe?',
    blogFaq: 'Blog & FAQ',
    prototypeShowcase: 'Prototype Demo',
    nearbyHospitals: 'Nearby Hospitals',
    generateQR: 'Generate QR Code',
    securityFeatures: 'Security Features',
    healthAwareness: 'Health Awareness'
  },
  hi: {
    welcome: 'केरल प्रवासी स्वास्थ्य पोर्टल में आपका स्वागत है',
    welcomeRoghar: 'रोघर में आपका स्वागत है',
    startConsultation: 'परामर्श शुरू करें',
    emergencySOS: 'आपातकालीन SOS',
    nearbyServices: 'नजदीकी चिकित्सा सेवाएं',
    reminders: 'रिमाइंडर',
    addReminder: 'रिमाइंडर जोड़ें',
    voiceInput: 'आवाज इनपुट',
    speakToMe: 'मुझसे बात करें',
    listening: 'सुन रहा है...',
    uploadReport: 'रिपोर्ट अपलोड करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    generateQR: 'QR कोड जेनरेट करें',
    feedback: 'प्रतिक्रिया',
    healthTips: 'स्वास्थ्य सुझाव',
    governmentSchemes: 'सरकारी योजनाएं',
    leaveComment: 'टिप्पणी छोड़ें',
    videoCall: 'वीडियो कॉल',
    joinCall: 'कॉल में शामिल हों',
    endCall: 'कॉल समाप्त करें',
    workerLogin: 'श्रमिक लॉगिन',
    doctorLogin: 'डॉक्टर लॉगिन',
    workerSignup: 'श्रमिक साइन अप',
    doctorSignup: 'डॉक्टर साइन अप',
    signup: 'साइन अप',
    login: 'लॉगिन',
    aadharNumber: 'आधार नंबर',
    abhaId: 'आभा आईडी',
    password: 'पासवर्ड',
    name: 'नाम',
    phone: 'फोन नंबर',
    address: 'पता',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    testReports: 'टेस्ट रिपोर्ट',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    dashboard: 'डैशबोर्ड',
    logout: 'लॉगआउट',
    appointments: 'अपॉइंटमेंट',
    patients: 'मरीज़',
    profile: 'प्रोफाइल',
    language: 'भाषा',
    english: 'अंग्रेजी',
    hindi: 'हिंदी',
    malayalam: 'मलयालम',
    bengali: 'बंगाली',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    date: 'तारीख',
    time: 'समय',
    doctor: 'डॉक्टर',
    hospital: 'अस्पताल',
    status: 'स्थिति',
    pending: 'लंबित',
    confirmed: 'पुष्ट',
    completed: 'पूर्ण',
    selectHospital: 'अस्पताल चुनें',
    selectDoctor: 'डॉक्टर चुनें',
    selectDate: 'तारीख चुनें',
    selectTime: 'समय चुनें',
    reason: 'मुलाकात का कारण',
    symptoms: 'लक्षण',
    uploadReport: 'रिपोर्ट अपलोड करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    reportDate: 'रिपोर्ट की तारीख',
    reportType: 'रिपोर्ट का प्रकार',
    bloodTest: 'रक्त जांच',
    xray: 'एक्स-रे',
    mri: 'एमआरआई',
    ct: 'सीटी स्कैन',
    other: 'अन्य',
    medicineInfo: 'दवा की जानकारी',
    searchMedicines: 'दवाएं खोजें',
    filterByType: 'प्रकार के अनुसार फ़िल्टर करें',
    viewDetails: 'विवरण देखें',
    dosage: 'खुराक',
    sideEffects: 'साइड इफेक्ट्स',
    precautions: 'सावधानियां',
    description: 'विवरण',
    usage: 'उपयोग',
    noMedicineFound: 'कोई जानकारी उपलब्ध नहीं है, कृपया कोई अन्य दवा आज़माएं',
    medicalDisclaimer: 'चिकित्सा अस्वीकरण',
    mockupDashboard: 'लाइव डैशबोर्ड',
    hospitalMap: 'अस्पताल मानचित्र',
    qrGenerator: 'क्यूआर जेनरेटर',
    whySafe: 'क्यों सुरक्षित?',
    blogFaq: 'ब्लॉग और FAQ',
    prototypeShowcase: 'प्रोटोटाइप डेमो',
    nearbyHospitals: 'नजदीकी अस्पताल',
    generateQR: 'क्यूआर कोड जेनरेट करें',
    securityFeatures: 'सुरक्षा सुविधाएं',
    healthAwareness: 'स्वास्थ्य जागरूकता'
  },
  ml: {
    welcome: 'കേരള കുടിയേറ്റ ആരോഗ്യ പോർട്ടലിലേക്ക് സ്വാഗതം',
    welcomeRoghar: 'രോഘറിലേക്ക് സ്വാഗതം',
    startConsultation: 'കൺസൾട്ടേഷൻ ആരംഭിക്കുക',
    emergencySOS: 'എമർജൻസി SOS',
    nearbyServices: 'അടുത്തുള്ള മെഡിക്കൽ സേവനങ്ങൾ',
    reminders: 'ഓർമ്മപ്പെടുത്തലുകൾ',
    addReminder: 'ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',
    voiceInput: 'വോയ്സ് ഇൻപുട്ട്',
    speakToMe: 'എന്നോട് സംസാരിക്കുക',
    listening: 'കേൾക്കുന്നു...',
    uploadReport: 'റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    generateQR: 'QR കോഡ് ജനറേറ്റ് ചെയ്യുക',
    feedback: 'ഫീഡ്ബാക്ക്',
    healthTips: 'ആരോഗ്യ നുറുങ്ങുകൾ',
    governmentSchemes: 'സർക്കാർ പദ്ധതികൾ',
    leaveComment: 'അഭിപ്രായം രേഖപ്പെടുത്തുക',
    videoCall: 'വീഡിയോ കോൾ',
    joinCall: 'കോളിൽ ചേരുക',
    endCall: 'കോൾ അവസാനിപ്പിക്കുക',
    workerLogin: 'തൊഴിലാളി ലോഗിൻ',
    doctorLogin: 'ഡോക്ടർ ലോഗിൻ',
    workerSignup: 'തൊഴിലാളി സൈൻ അപ്പ്',
    doctorSignup: 'ഡോക്ടർ സൈൻ അപ്പ്',
    signup: 'സൈൻ അപ്പ്',
    login: 'ലോഗിൻ',
    aadharNumber: 'ആധാർ നമ്പർ',
    abhaId: 'അഭാ ഐഡി',
    password: 'പാസ്‌വേഡ്',
    name: 'പേര്',
    phone: 'ഫോൺ നമ്പർ',
    address: 'വിലാസം',
    healthRecords: 'ആരോഗ്യ രേഖകൾ',
    testReports: 'ടെസ്റ്റ് റിപ്പോർട്ടുകൾ',
    bookAppointment: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    dashboard: 'ഡാഷ്ബോർഡ്',
    logout: 'ലോഗൗട്ട്',
    appointments: 'അപ്പോയിന്റ്മെന്റുകൾ',
    patients: 'രോഗികൾ',
    profile: 'പ്രൊഫൈൽ',
    language: 'ഭാഷ',
    english: 'ഇംഗ്ലീഷ്',
    hindi: 'ഹിന്ദി',
    malayalam: 'മലയാളം',
    bengali: 'ബംഗാളി',
    submit: 'സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    save: 'സേവ് ചെയ്യുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    view: 'കാണുക',
    date: 'തീയതി',
    time: 'സമയം',
    doctor: 'ഡോക്ടർ',
    hospital: 'ആശുപത്രി',
    status: 'നില',
    pending: 'തീർപ്പുകൽപ്പിക്കാത്ത',
    confirmed: 'സ്ഥിരീകരിച്ചു',
    completed: 'പൂർത്തിയായി',
    selectHospital: 'ആശുപത്രി തിരഞ്ഞെടുക്കുക',
    selectDoctor: 'ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
    selectDate: 'തീയതി തിരഞ്ഞെടുക്കുക',
    selectTime: 'സമയം തിരഞ്ഞെടുക്കുക',
    reason: 'സന്ദർശനത്തിന്റെ കാരണം',
    symptoms: 'ലക്ഷണങ്ങൾ',
    uploadReport: 'റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    reportDate: 'റിപ്പോർട്ട് തീയതി',
    reportType: 'റിപ്പോർട്ട് തരം',
    bloodTest: 'രക്തപരിശോധന',
    xray: 'എക്സ്-റേ',
    mri: 'എംആർഐ',
    ct: 'സിടി സ്കാൻ',
    other: 'മറ്റുള്ളവ',
    medicineInfo: 'മരുന്നിന്റെ വിവരങ്ങൾ',
    searchMedicines: 'മരുന്നുകൾ തിരയുക',
    filterByType: 'തരം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    dosage: 'ഡോസേജ്',
    sideEffects: 'പാർശ്വഫലങ്ങൾ',
    precautions: 'മുൻകരുതലുകൾ',
    description: 'വിവരണം',
    usage: 'ഉപയോഗം',
    noMedicineFound: 'വിവരങ്ങൾ ലഭ്യമല്ല, ദയവായി മറ്റൊരു മരുന്ന് പരീക്ഷിക്കുക',
    medicalDisclaimer: 'മെഡിക്കൽ നിരാകരണം',
    mockupDashboard: 'ലൈവ് ഡാഷ്ബോർഡ്',
    hospitalMap: 'ആശുപത്രി മാപ്പ്',
    qrGenerator: 'ക്യുആർ ജനറേറ്റർ',
    whySafe: 'എന്തുകൊണ്ട് സുരക്ഷിതം?',
    blogFaq: 'ബ്ലോഗും FAQ യും',
    prototypeShowcase: 'പ്രോട്ടോടൈപ്പ് ഡെമോ',
    nearbyHospitals: 'അടുത്തുള്ള ആശുപത്രികൾ',
    generateQR: 'ക്യുആർ കോഡ് ജനറേറ്റ് ചെയ്യുക',
    securityFeatures: 'സുരക്ഷാ സവിശേഷതകൾ',
    healthAwareness: 'ആരോഗ്യ അവബോധം'
  },
  bn: {
    welcome: 'কেরালা অভিবাসী স্বাস্থ্য পোর্টালে স্বাগতম',
    welcomeRoghar: 'রোঘরে স্বাগতম',
    startConsultation: 'পরামর্শ শুরু করুন',
    emergencySOS: 'জরুরি SOS',
    nearbyServices: 'কাছাকাছি চিকিৎসা সেবা',
    reminders: 'অনুস্মারক',
    addReminder: 'অনুস্মারক যোগ করুন',
    voiceInput: 'ভয়েস ইনপুট',
    speakToMe: 'আমার সাথে কথা বলুন',
    listening: 'শুনছি...',
    uploadReport: 'রিপোর্ট আপলোড করুন',
    downloadReport: 'রিপোর্ট ডাউনলোড করুন',
    generateQR: 'QR কোড তৈরি করুন',
    feedback: 'মতামত',
    healthTips: 'স্বাস্থ্য টিপস',
    governmentSchemes: 'সরকারি প্রকল্প',
    leaveComment: 'মন্তব্য করুন',
    videoCall: 'ভিডিও কল',
    joinCall: 'কলে যোগ দিন',
    endCall: 'কল শেষ করুন',
    workerLogin: 'শ্রমিক লগইন',
    doctorLogin: 'ডাক্তার লগইন',
    workerSignup: 'শ্রমিক সাইন আপ',
    doctorSignup: 'ডাক্তার সাইন আপ',
    signup: 'সাইন আপ',
    login: 'লগইন',
    aadharNumber: 'আধার নম্বর',
    abhaId: 'আভা আইডি',
    password: 'পাসওয়ার্ড',
    name: 'নাম',
    phone: 'ফোন নম্বর',
    address: 'ঠিকানা',
    healthRecords: 'স্বাস্থ্য রেকর্ড',
    testReports: 'পরীক্ষার রিপোর্ট',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    dashboard: 'ড্যাশবোর্ড',
    logout: 'লগআউট',
    appointments: 'অ্যাপয়েন্টমেন্ট',
    patients: 'রোগী',
    profile: 'প্রোফাইল',
    language: 'ভাষা',
    english: 'ইংরেজি',
    hindi: 'হিন্দি',
    malayalam: 'মালায়ালাম',
    bengali: 'বাংলা',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    view: 'দেখুন',
    date: 'তারিখ',
    time: 'সময়',
    doctor: 'ডাক্তার',
    hospital: 'হাসপাতাল',
    status: 'অবস্থা',
    pending: 'অপেক্ষমান',
    confirmed: 'নিশ্চিত',
    completed: 'সম্পন্ন',
    selectHospital: 'হাসপাতাল নির্বাচন করুন',
    selectDoctor: 'ডাক্তার নির্বাচন করুন',
    selectDate: 'তারিখ নির্বাচন করুন',
    selectTime: 'সময় নির্বাচন করুন',
    reason: 'দেখার কারণ',
    symptoms: 'লক্ষণ',
    reportDate: 'রিপোর্টের তারিখ',
    reportType: 'রিপোর্টের ধরন',
    bloodTest: 'রক্ত পরীক্ষা',
    xray: 'এক্স-রে',
    mri: 'এমআরআই',
    ct: 'সিটি স্ক্যান',
    other: 'অন্যান্য',
    medicineInfo: 'ওষুধের তথ্য',
    searchMedicines: 'ওষুধ খুঁজুন',
    filterByType: 'ধরন অনুযায়ী ফিল্টার করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    dosage: 'ডোজ',
    sideEffects: 'পার্শ্বপ্রতিক্রিয়া',
    precautions: 'সতর্কতা',
    description: 'বর্ণনা',
    usage: 'ব্যবহার',
    noMedicineFound: 'কোন তথ্য পাওয়া যায়নি, অন্য ওষুধ চেষ্টা করুন',
    medicalDisclaimer: 'চিকিৎসা দাবিত্যাগ',
    mockupDashboard: 'লাইভ ড্যাশবোর্ড',
    hospitalMap: 'হাসপাতালের মানচিত্র',
    qrGenerator: 'QR জেনারেটর',
    whySafe: 'কেন নিরাপদ?',
    blogFaq: 'ব্লগ ও FAQ',
    prototypeShowcase: 'প্রোটোটাইপ ডেমো',
    nearbyHospitals: 'কাছাকাছি হাসপাতাল',
    securityFeatures: 'নিরাপত্তা বৈশিষ্ট্য',
    healthAwareness: 'স্বাস্থ্য সচেতনতা'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || key
  }

  const changeLanguage = (lang) => {
    setLanguage(lang)
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}